### ISSUE TITLE
Remove nth occurrence of an object from a collection/object.

### ISSUE THREAD

**Issue by elrayle** [samvera/hydra-pcdm#102]
Objects can repeat in a collection and in an object.  The RemoveObjectFromCollection and RemoveObjectFromObject services need to support specifying which occurrence to remove.  See notes in those services and see the following tests in remove_object_from_collection_spec and remove_object_from_object_spec.

  xit 'should remove first occurrence'
  xit 'should remove last occurrence'
  xit 'should remove nth occurrence'

**Comment by elrayle** [comment]
DEPENDENCY:  https://github.com/projecthydra-labs/activefedora-aggregation/issues/46 for more information.

Proposed syntax:
```ruby
# delete 2nd occurrence of do_child1
do_parent.members.delete( do_child1, 2 )   # => do_child1
```

**Comment by jrgriffiniii** [comment]
Closing this due to the age of the issue (I am sorry, please let me know should this be reopened).
