### ISSUE TITLE
members.delete should return values consistent with Array and Hash

### ISSUE THREAD

**Issue by elrayle** [samvera/hydra-pcdm#103]
It is expected that members.delete and related_objects.delete will return...
- return child_collection/object when successful delete
- return nil if child_collection/object does not exist in parent_collection/object
- raise error for any other problems

See related issue https://github.com/projecthydra-labs/activefedora-aggregation/issues/34.

Workaround to provide this behavior is in the hydra:pcdm remove services.  They will need to be updated once the ActiveFedora issue is fixed.

Effected classes:
- RemoveCollectionFromCollection
- RemoveObjectFromCollection
- RemoveRelatedObjectFromCollection
- RemoveObjectFromObject
- RemoveRelatedObjectFromObject

Tested by:
- services/collection/remove_collection.rb  -- context 'when collection is missing'
- services/collection/remove_object.rb  -- context 'when object is missing'
- services/collection/remove_related_object.rb  -- context 'when related object is missing'
- services/object/remove_object.rb  -- context 'when object is missing'
- services/object/remove_related_object.rb  -- context 'when related object is missing'

NOTE: These tests pass now because of the workaround in each of the Remove services.

**Comment by elrayle** [comment]
See related issue https://github.com/projecthydra-labs/activefedora-aggregation/issues/35

**Comment by elrayle** [comment]
The source of the issue  https://github.com/projecthydra-labs/activefedora-aggregation/issues/35 at some point started working and has been closed.  The kludge for the service objects can be removed.

**Comment by jrgriffiniii** [comment]
Closing this due to the age of the issue (I am sorry, please let me know should this be reopened).
