### ISSUE TITLE
Remove the Get* services

### ISSUE THREAD

**Issue by jcoyne** [samvera/hydra-pcdm#110]
The models already provide this service. We're wandering into the [Anemic Domain Model](http://www.martinfowler.com/bliki/AnemicDomainModel.html) and [Poltergeist](http://www.darxstudios.com/darx-studios/2014/8/25/antipatterns-poltergeists) antipatterns.

I propose we remove:

```
lib/hydra/pcdm/services/collection/get_collections.rb
lib/hydra/pcdm/services/collection/get_objects.rb
lib/hydra/pcdm/services/collection/get_related_objects.rb
lib/hydra/pcdm/services/object/get_objects.rb
lib/hydra/pcdm/services/object/get_related_objects.rb
```

@elrayle do you agree?

**Comment by terrellt** [comment]
@jcoyne These are now deprecated, can we close it?
