### ISSUE TITLE
Add AdministrativeSet model

### ISSUE THREAD

**Issue by dchandekstark** [samvera/hydra-pcdm#111]
https://wiki.duraspace.org/display/FF/Portland+Common+Data+Model#PortlandCommonDataModel-pcdm:AdministrativeSet

**Comment by jrgriffiniii** [comment]
AdminSets, modeled in Hyrax, could likely be extended to address the use cases for PCDM AdministrativeSets: https://github.com/samvera/hyrax/blob/master/app/models/admin_set.rb
