### ISSUE TITLE
Maintain PCDM::X#ancestor? API

### ISSUE THREAD

**Issue by tpendragon** [samvera/hydra-pcdm#145]
``` ruby
# @param [#members] object Potential ancestor
# @return [Boolean]
def ancestor?(object)
end
```

If we keep this as part of the API we can remove the direct AncestorChecker references in the relation.

**Comment by blancoj** [comment]
Could you take a look at my changes and let me know if I'm on the right track.  Here's the moved method:  https://github.com/blancoj/hydra-pcdm/blob/experiment/lib/hydra/pcdm/models/concerns/pcdm_behavior.rb#L33 and here is an rspec to check it https://github.com/blancoj/hydra-pcdm/blob/experiment/spec/hydra/pcdm/models/object_jose.rb

Also, should I remove these completely: lib/hydra/pcdm/ancestor_checker.rb, and spec/hydra/pcdm/ancestor_checker_spec.rb

**Comment by terrellt** [comment]
@blancoj I'd keep the AncestorChecker, have #ancestor? use it, and then change https://github.com/blancoj/hydra-pcdm/blob/experiment/lib/hydra/pcdm/validators/ancestor_validator.rb#L15 to just do `owner.ancestor?(record)`

**Comment by blancoj** [comment]
@terrellt when you say have #ancestor? use it, do you mean the method ancestor? I proposed in here:

https://github.com/blancoj/hydra-pcdm/blob/experiment/lib/hydra/pcdm/models/concerns/pcdm_behavior.rb#L33

should use AncestorChecker?

**Comment by elrayle** [comment]
@blancoj I'm not sure what your question is with this, but if you are looking to test full coverage, you can look at the set of tests in [collection_spec.rb](https://github.com/projecthydra-labs/hydra-pcdm/blob/master/spec/hydra/pcdm/models/collection_spec.rb) with description 'adding collections that are ancestors' (starting around line 115)

**Comment by grosscol** [comment]
@terrellt So keep the functionality in the AncestorChecker? Have the `ancestor?` method in PCDM behavior call the AncestorChecker method?  I think I misinterpreted this issue when I first read it, and probably sent @blancoj off on the wrong direction to begin with.

**Comment by terrellt** [comment]
@grosscol That's what I would do, yeah.

**Comment by blancoj** [comment]
I changed this:
https://github.com/blancoj/hydra-pcdm/blob/issue_145/lib/hydra/pcdm/validators/ancestor_validator.rb#L17


But I'm not sure how to make this work.  Once you're in pcdm_behavior how
do you maintain the relationship between owner and record?:

https://github.com/blancoj/hydra-pcdm/blob/issue_145/lib/hydra/pcdm/models/concerns/pcdm_behavior.rb#L45

**Comment by jrgriffiniii** [comment]
Closing this due to the age of the issue (I am sorry, please let me know should this be reopened).
