### ISSUE TITLE
Use Case: Making Archivematica output available in a hydra head

### ISSUE THREAD

**Issue by barmintor** [samvera/hydra-pcdm#192]
# User Story

I need to ingest a disk device processed by Archivematica into our repository. In my hydra-head, I need to present a UI that allows the Bag content to be navigated as if it were a file system.
## How does a BagIt archive map to PCDM concepts?

Our initial approach has been to create an AdministrativeSet for the Bag, that contains GenericFile objects for all the listings in the manifest.
## How does Archivematica's output impact this mapping?

Archivematica includes a METS file elaborating the manifest listing with the original names of the files, some description of the Bag, file technical metadata, and a reckoning of what files are derived content and what are original.

This has two effects on the PCDM mapping: First, GenericFile objects are created only for the original content. The derived content is ingested as related files on the GenericFile. The path components of the original file paths are indexed for the discovery interface, as are the PRONOM data (mapped to the PCDM file type vocabulary). The GenericFiles are still contained by the AdministrativeSet, but they are members of a Collection.

The Collection is created describing (iana:describes an AdministrativeSet) the Bag and its structure according to the original file paths. Since the directories have no independent description, they are represented as ordering ore:Proxy objects for the GenericFile members. Rather than the singly linked list representation of order, these Proxies use NEPOMUK/Semantic Desktop relationships to build a hierarchy within which immediate children are sortable (like a desktop file system).
## What about multi-bag aggregations?

Multiple Bags can be composed into derivative Collections. These Collection indicate their lineage to the original Bag's Collection.
## What about when the GenericFiles have a description, or are part of identifiable works?

When descriptive metadata is available, an additional Collection of GenericWorks is created. These works have descriptions and GenericFile members. If a GenericFile has extractable text, the GenericFile and the GenericWorks it is a member of are discoverable via that text. The Collections are discoverable only via their own descriptions. The GenericFile objects can be navigated via the "file system" Proxies or discovered via fulltext or format search.

**Comment by barmintor** [comment]
A public -facing example: https://dlc.library.columbia.edu/ifp/ldpd:495805

**Comment by jrgriffiniii** [comment]
Closing this due to the age of the issue (I am sorry, please let me know should this be reopened).
