### ISSUE TITLE
Specs failing since build 805, activesupport 5.2.0

### ISSUE THREAD

**Issue by botimer** [samvera/hydra-pcdm#251]
The Travis builds have been breaking since [https://travis-ci.org/samvera/hydra-pcdm/builds/365265336](build 805). There were no direct code changes between this and the successful [https://travis-ci.org/samvera/hydra-pcdm/builds/362286059](build 804).

The relevant change, as far as I have found, is that `active-fedora-12.0.1` depends on `activesupport <6, >= 4.2.4`. The breakage appears to coincide with the release of 5.2.0, and local builds pass when limiting to < 5.2.

In some poking around, I haven't found a fix yet. Requiring `core_ext/module/remove_method` got past the missing method problem but ~40 examples fail after that, so more attention is needed.

**Comment by jrgriffiniii** [comment]
As detailed by @cjcolvar in https://github.com/samvera/hydra-pcdm/issues/248#issuecomment-386054216, I have confirmed that this is the case with a passing build using the following: https://github.com/jrgriffiniii/hydra-pcdm/tree/issues-251-jrgriffiniii-fix-specs

It may be blocked by https://github.com/samvera/active_fedora/issues/1306 as a result
