### ISSUE TITLE
Get Test Coverage above 90%

### ISSUE THREAD

**Issue by botimer** [samvera/hydra-pcdm#252]
Currently, coveralls sees coverage at 71%. Weigh in on whether this is sufficient or which areas could use additional testing.

**Comment by tpendragon** [comment]
@mark-dce Is 71% test coverage sufficient for this project?

**Comment by tpendragon** [comment]
This might be a side effect of the failing tests.

**Comment by mark-dce** [comment]
Yes - I would like to increase test coverage to something above 90% if possible
