### ISSUE TITLE
Should related objects be solrized?

### ISSUE THREAD

**Issue by elrayle** [samvera/hydra-pcdm#90]
See test hydra/pcdm/services/collection/add_related_object_spec.rb  test: it 'should solrize member ids'
See test hydra/pcdm/services/object/add_related_object_spec.rb  test: it 'should solrize member ids'

Those tests currently check that the objects and collections were solrized, and that related objects are not part of the objects and collections index.  Should there be a related_objects index? 

Files don't appear to have ids and therefore are not tested for inclusion in an index.  Is that correct?

**Comment by jrgriffiniii** [comment]
Closing this due to the age of the issue (I am sorry, please let me know should this be reopened).
