### ISSUE TITLE
Use premis:hasSize for file size

### ISSUE THREAD

**Issue by escowles** [samvera/hydra-pcdm#95]
Now that https://github.com/fcrepo4/fcrepo4/pull/791 is merged, the technical metadata is be mostly consistent with the Technical Metadata Application Profile and fcrepo4 master branch.  But I think there is one change we should make beyond https://github.com/projecthydra-labs/hydra-pcdm/commit/edeb25d6b01b9b8cc9bc99cd888a1aee3f9bf6a9

We should use premis:hasSize as a read-only copy of the fcrepo4 server-managed file size, instead of using ebucore:fileSize

**Comment by jrgriffiniii** [comment]
https://github.com/samvera/hydra-pcdm/commit/f0a0e3350fabaa67146d47b34a749f8dcd53274b#diff-c63a4439c7f7257cacd1eb2e2b7e9a73 shifted this to ActiveFedora.
